#logback配置文件的地址
logging:
  config: classpath:logback-spring.xml
  level:
    com.lwl.base.project.mapper: debug
spring:
  #应用名
  application:
    name: base-project
  #日志环境
  profiles:
    active: dev # dev|test|prd
  #数据库
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.198.29:3306/base_api?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: MysqL@951QwdC
    #hikari配置
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #redis settings
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lwl.base.project.entity.pojo
  configuration:
    map-underscore-to-camel-case: true
